version: "3"

services:
    account-service:
        build: .
        env_file: .env
        environment:
            DB_HOST: account-db
        depends_on:
            account-migrate:
                condition: service_completed_successfully
        command: go test ./... -v
