name: Build and push

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Test
              run: make test

            - name: Login to Docker Hub
              if: failure()
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USER }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up Docker Buildx
              if: failure()
              uses: docker/setup-buildx-action@v2

            - name: Build and push
              if: failure()
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKER_USER }}/micro-it-fl_account-service:latest
